variable "region" {}
variable "env" {}
variable "vpc_cidr" {}
variable "vpc_name" {}
variable "Public_Subnet_Cidr" {}
variable "Private_Subnet_Cidr" {}
variable "az" {}
variable "ami" {}
variable "key" {}